// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/service/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/service/user.go -destination=internal/app/service/mocks/mock_user_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/shirr9/pr-reviewer-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryForService is a mock of UserRepositoryForService interface.
type MockUserRepositoryForService struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryForServiceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryForServiceMockRecorder is the mock recorder for MockUserRepositoryForService.
type MockUserRepositoryForServiceMockRecorder struct {
	mock *MockUserRepositoryForService
}

// NewMockUserRepositoryForService creates a new mock instance.
func NewMockUserRepositoryForService(ctrl *gomock.Controller) *MockUserRepositoryForService {
	mock := &MockUserRepositoryForService{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryForServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryForService) EXPECT() *MockUserRepositoryForServiceMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockUserRepositoryForService) FindByID(ctx context.Context, userID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryForServiceMockRecorder) FindByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepositoryForService)(nil).FindByID), ctx, userID)
}

// SetIsActive mocks base method.
func (m *MockUserRepositoryForService) SetIsActive(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserRepositoryForServiceMockRecorder) SetIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserRepositoryForService)(nil).SetIsActive), ctx, userID, isActive)
}

// MockPullRequestRepositoryForUser is a mock of PullRequestRepositoryForUser interface.
type MockPullRequestRepositoryForUser struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryForUserMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryForUserMockRecorder is the mock recorder for MockPullRequestRepositoryForUser.
type MockPullRequestRepositoryForUserMockRecorder struct {
	mock *MockPullRequestRepositoryForUser
}

// NewMockPullRequestRepositoryForUser creates a new mock instance.
func NewMockPullRequestRepositoryForUser(ctrl *gomock.Controller) *MockPullRequestRepositoryForUser {
	mock := &MockPullRequestRepositoryForUser{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryForUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepositoryForUser) EXPECT() *MockPullRequestRepositoryForUserMockRecorder {
	return m.recorder
}

// FindByReviewer mocks base method.
func (m *MockPullRequestRepositoryForUser) FindByReviewer(ctx context.Context, reviewerID string) ([]*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReviewer indicates an expected call of FindByReviewer.
func (mr *MockPullRequestRepositoryForUserMockRecorder) FindByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReviewer", reflect.TypeOf((*MockPullRequestRepositoryForUser)(nil).FindByReviewer), ctx, reviewerID)
}
