// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/service/pull_request.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/service/pull_request.go -destination=internal/app/service/mocks/mock_pull_request_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/shirr9/pr-reviewer-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pr *models.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pr)
}

// Exists mocks base method.
func (m *MockPullRequestRepository) Exists(ctx context.Context, prID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, prID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockPullRequestRepositoryMockRecorder) Exists(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockPullRequestRepository)(nil).Exists), ctx, prID)
}

// FindByID mocks base method.
func (m *MockPullRequestRepository) FindByID(ctx context.Context, prID string) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, prID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByID(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByID), ctx, prID)
}

// UpdateStatus mocks base method.
func (m *MockPullRequestRepository) UpdateStatus(ctx context.Context, prID, status string, mergedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, prID, status, mergedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPullRequestRepositoryMockRecorder) UpdateStatus(ctx, prID, status, mergedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPullRequestRepository)(nil).UpdateStatus), ctx, prID, status, mergedAt)
}

// MockReviewerRepository is a mock of ReviewerRepository interface.
type MockReviewerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewerRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewerRepositoryMockRecorder is the mock recorder for MockReviewerRepository.
type MockReviewerRepositoryMockRecorder struct {
	mock *MockReviewerRepository
}

// NewMockReviewerRepository creates a new mock instance.
func NewMockReviewerRepository(ctrl *gomock.Controller) *MockReviewerRepository {
	mock := &MockReviewerRepository{ctrl: ctrl}
	mock.recorder = &MockReviewerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewerRepository) EXPECT() *MockReviewerRepositoryMockRecorder {
	return m.recorder
}

// AssignReviewer mocks base method.
func (m *MockReviewerRepository) AssignReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewer indicates an expected call of AssignReviewer.
func (mr *MockReviewerRepositoryMockRecorder) AssignReviewer(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).AssignReviewer), ctx, prID, reviewerID)
}

// GetPRsByReviewer mocks base method.
func (m *MockReviewerRepository) GetPRsByReviewer(ctx context.Context, reviewerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRsByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRsByReviewer indicates an expected call of GetPRsByReviewer.
func (mr *MockReviewerRepositoryMockRecorder) GetPRsByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRsByReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).GetPRsByReviewer), ctx, reviewerID)
}

// GetReviewers mocks base method.
func (m *MockReviewerRepository) GetReviewers(ctx context.Context, prID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewers", ctx, prID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewers indicates an expected call of GetReviewers.
func (mr *MockReviewerRepositoryMockRecorder) GetReviewers(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewers", reflect.TypeOf((*MockReviewerRepository)(nil).GetReviewers), ctx, prID)
}

// IsAssigned mocks base method.
func (m *MockReviewerRepository) IsAssigned(ctx context.Context, prID, reviewerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAssigned", ctx, prID, reviewerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAssigned indicates an expected call of IsAssigned.
func (mr *MockReviewerRepositoryMockRecorder) IsAssigned(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAssigned", reflect.TypeOf((*MockReviewerRepository)(nil).IsAssigned), ctx, prID, reviewerID)
}

// ReplaceReviewer mocks base method.
func (m *MockReviewerRepository) ReplaceReviewer(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceReviewer", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceReviewer indicates an expected call of ReplaceReviewer.
func (mr *MockReviewerRepositoryMockRecorder) ReplaceReviewer(ctx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceReviewer", reflect.TypeOf((*MockReviewerRepository)(nil).ReplaceReviewer), ctx, prID, oldReviewerID, newReviewerID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindActiveCandidatesForReassignment mocks base method.
func (m *MockUserRepository) FindActiveCandidatesForReassignment(ctx context.Context, teamName string, excludeUserIDs []string) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveCandidatesForReassignment", ctx, teamName, excludeUserIDs)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveCandidatesForReassignment indicates an expected call of FindActiveCandidatesForReassignment.
func (mr *MockUserRepositoryMockRecorder) FindActiveCandidatesForReassignment(ctx, teamName, excludeUserIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveCandidatesForReassignment", reflect.TypeOf((*MockUserRepository)(nil).FindActiveCandidatesForReassignment), ctx, teamName, excludeUserIDs)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, userID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, userID)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactor) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactorMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactor)(nil).WithinTransaction), ctx, fn)
}
