// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/service/team.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/service/team.go -destination=internal/app/service/mocks/mock_team_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/shirr9/pr-reviewer-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdateTeam mocks base method.
func (m *MockTeamRepository) CreateOrUpdateTeam(ctx context.Context, team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateTeam indicates an expected call of CreateOrUpdateTeam.
func (mr *MockTeamRepositoryMockRecorder) CreateOrUpdateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTeam", reflect.TypeOf((*MockTeamRepository)(nil).CreateOrUpdateTeam), ctx, team)
}

// GetTeamByName mocks base method.
func (m *MockTeamRepository) GetTeamByName(ctx context.Context, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamRepositoryMockRecorder) GetTeamByName(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamByName), ctx, teamName)
}

// IsExists mocks base method.
func (m *MockTeamRepository) IsExists(ctx context.Context, teamName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExists", ctx, teamName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExists indicates an expected call of IsExists.
func (mr *MockTeamRepositoryMockRecorder) IsExists(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExists", reflect.TypeOf((*MockTeamRepository)(nil).IsExists), ctx, teamName)
}
